### ISSUE TITLE
🐛[Bug]:  testing for GSSoC label

### ISSUE THREAD

**Issue by TonyStark-47** [TonyStark-47/ConvoForm#2]
### Is there an existing issue for this?

- [X] No, I have searched the existing issues

### Describe the bug

is it asssigning the `gssoc` and `level1` label or not?

### Expected behavior

a

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by growupanand** [comment]
@TonyStark-47, can you assign this to me for testing the workflow. I will create a pull request and you will merge this into your repo. Lets see if it will do as expected. Then we will merge into the source repo.

**Comment by TonyStark-47** [comment]
@growupanand , assigned!

**Comment by growupanand** [comment]
@TonyStark-47 , It looks like I am not able to fork your repo, since the source repo is already in my profile. Can you please create a test PR for me? and merge it into your repo.

**Comment by TonyStark-47** [comment]
@growupanand , ok

**Comment by TonyStark-47** [comment]
@growupanand , now you can see that its working..
